server:
  port: 8080

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://mascotas-datos:5432/mascotas}
    driverClassName: org.postgresql.Driver
    username: ${SPRING_DATASOURCE_USERNAME:mascotas_user}
    password: ${SPRING_DATASOURCE_PASSWORD:mascotas_pass}

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    open-in-view: false

cors:
  allowed-origins: ${CORS_ORIGINS:http://localhost:3000}

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs